### ISSUE TITLE
Less Mixins

### ISSUE THREAD

**Issue by dcneiner** [LeanKit-Labs/touchstone#3]
@LeanKit-Hunter brought up the standard that if using a Mixin, it should be the first thing in the CSS Block, followed by a blank line then any new rules. This makes a lot of sense if we want to use mixins. Adding it here for any discussion before adding to the Style Guide.
## Less Mixins

``` less
.someclass {
    ...
}

.component {
  .someclass;

  color: red;
}
```
